//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoParts.AppDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoPartsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutoPartsTable()
        {
            this.Sale = new HashSet<Sale>();
            this.Supply = new HashSet<Supply>();
        }
    
        public int IdAutoPart { get; set; }
        public Nullable<int> IdTypeAutoPart { get; set; }
        public string NameAutoPart { get; set; }
        public Nullable<int> CountAutoPart { get; set; }
        public Nullable<decimal> PriceAutoPart { get; set; }
    
        public virtual TypeAutoParts TypeAutoParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply> Supply { get; set; }
    }
}
