//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoParts.AppDate
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoPartsDBEntities1 : DbContext
    {
        public AutoPartsDBEntities1()
            : base("name=AutoPartsDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutoPartsTable> AutoPartsTable { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Providers> Providers { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<TypeAutoParts> TypeAutoParts { get; set; }
    }
}
