//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoParts.AppDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int IdSale { get; set; }
        public Nullable<int> IdAutoPart { get; set; }
        public Nullable<int> IdTypeAutoPart { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<System.DateTime> DateSale { get; set; }
        public Nullable<int> CountAutoPartSale { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual AutoPartsTable AutoPartsTable { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual TypeAutoParts TypeAutoParts { get; set; }
    }
}
