//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoParts.AppDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int IdSupply { get; set; }
        public Nullable<int> IdProvider { get; set; }
        public Nullable<int> IdAutoPart { get; set; }
        public Nullable<int> IdTypeAutoPart { get; set; }
        public Nullable<System.DateTime> DateSupply { get; set; }
        public Nullable<int> CountAutoPartSupply { get; set; }
    
        public virtual AutoPartsTable AutoPartsTable { get; set; }
        public virtual Providers Providers { get; set; }
        public virtual TypeAutoParts TypeAutoParts { get; set; }
    }
}
